config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :notes

    authenticated :user do
      root 'notes#index', as: "authenticated_root"
    end
    
  root 'welcome#index'
    

  

end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :find_note, only: [:show, :edit, :update, :destroy]

	def index
		@notes = Note.where(user_id: current_user)
	end

	def show
	end

	def new
		@note = current_user.notes.build
	end

	def create
		@note = current_user.notes.build(note_params)
		if @note.save
			redirect_to @note
		else
			render 'new'
		end	
	end

	def edit
		
	end

	def update
		if @note.update(note_params)
			redirect_to @note
		else
			render 'edit'
		end
		
	end

	def destroy
		@note.destroy
		redirect_to notes_path
	end

private

	def find_note
		@note = Note.find(params[:id])
	end

	def note_params
		params.require(:note).permit(:title, :content, :user_id)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!5
%html
	%head
		%title My Note App
		= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Oxygen:400,700'
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
		- if flash[:notice]
			.notice= flash[:notice]
		.nav.navbar-inverse.my-nav
			.navbar-header
				.navbar-brand= link_to "My Notes App", root_path, class: "my-brand"
			%ul.nav.navbar-nav.navbar-right
				- if user_signed_in?
					%li= link_to "My Account", new_user_session_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
				- else
					%li= link_to "Log In", new_user_session_path
					%li= link_to "Sign Up", new_user_registration_path

		= yield

		.nav.navbar-inverse.navbar-fixed-bottom.my-footer
			

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
	= f.input :title
	= f.input :content
	= f.button :submit

app/views/notes/edit.html.haml
.container
	.col-md-6.col-md-offset-3.my-form
		%h1.my-notes Edit your note

		= render 'form'

		%br/
		%br/
		= link_to 'Back to Notes', notes_path

app/views/notes/index.html.haml
.all-notes
	.container.my-notes
		%h1 Welcome to your notes
		%br/
		.row
			- @notes.each do |note|
				.col-md-4
					.panel.panel-default
						.panel.body.my-panel
							%h2= link_to note.title, note, class: "my-link"
							%p.date= time_ago_in_words(note.created_at)

		= link_to "Create new note", new_note_path, class: "btn btn-default"

app/views/notes/new.html.haml
.container
	.row
		.col-md-6.col-md-offset-3.my-form
			%h1 Create a new note:

			= render 'form'

			%br/
			= link_to "Back to Notes", @note

app/views/notes/show.html.haml
.background-notes
	.container
		.row.my-notes
			%h1= @note.title
			%br/
			%p
			%q= @note.content
		%br/
		%br/
		.row.note-links
			= link_to "Back to Notes", notes_path, class: "btn btn-default"
			= link_to "Edit Note", edit_note_path(@note), class: "btn btn-primary"
			= link_to "Delete Note", note_path(@note), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"

app/views/welcome/index.html.haml
.marketing
	%h1.never-more Never more lost one note!

%h1.my-button= link_to "Sign Up!", new_user_registration_path, class: "btn, btn-DEFAULT"

.col-md-12
	.my-text
		Everything that you want. 
		%br/
		
		Make notes safe, fast and on the cloud.	